name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:  # 手動トリガーを有効化

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: '17'  # または必要な Java バージョン

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Release with Gradle
        run: ./gradlew assembleRelease

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            app/build/*

      - name: Upload Release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release-APK
          path: |
            app/build/outputs/apk/release
